apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: dcgm-exporter
  namespace: monitoring
spec:
  endpoints:
    - honorLabels: false
      interval: 15s
      path: /metrics
      port: metrics
      relabelings:
        - action: replace
          sourceLabels:
            - __meta_ec2_instance_id
          targetLabel: instance
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/component: dcgm-exporter
      app.kubernetes.io/instance: dcgm-exporter
      app.kubernetes.io/name: dcgm-exporter
