apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay-operator-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ray-project/kuberay
    targetRevision: v${kuberay_version}
    path: helm-chart/kuberay-operator/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - Replace=true
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
